sudo: required
services :
  - docker

before_install :
  - docker build -t chary123/multi-image -f ./client/Dockerfile.dev ./client
script : 
  - docker run chary123/multi-image npm test -- --coverage
#  - docker run -r CI=true chary123/multi-image npm test 

after_success :
  - docker build -t chary123/multi-client ./client
  - docker build -t chary123/multi-nginx ./nginx
  - docker build -t chary123/multi-server ./server
  - docker build -t chary123/multi-worker ./worker
#docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take the images nand push to docker hub
  - docker push chary123/multi-client
  - docker push chary123/multi-nginx
  - docker push chary123/multi-server
  - docker push chary123/multi-worker